package com.handling.exception;

import java.lang.*;

public class Main {
	
	   public static void main(String[] args) {
		   
		   
//		   int exception = 5/0;
//		   
//		   System.out.println("IL MIO CODICE GENERA UN ECCEZIONE" + exception);


//	        // EXEPTION BY ZERO
//	        try {
//	            int arithmetic = 6 / 0;
//	        } catch (ArithmeticException e) {
//
//
//	            System.out.println("EXCEPTION GOOD");
//
//	        }

//
//
//	        // EXEPTION ARRAY INDEX OF
//	        try {
//
//	            int[] array = new int[5];
//
//	            array[0] = 10;
//	            array[1] = 20;
//	            array[2] = 30;
//	            array[3] = 40;
//	            array[4] = 50;
//
//	            System.out.println(array[5]);
//
//	        } catch (Exception e) {
//
//
//	            System.out.println(" ARRAY EXCEPTION GOOD");
//
//	        }


	 //   }
//	   
//               try {
//           int[] array = new int[5];
//
//           array[0] = 10;
//           array[1] = 20;
//           array[2] = 30;
//           array[3] = 40;
//           array[4] = 50;
//
//           System.out.println(array[5]);
//               }
//               
//            catch (IndexOutOfBoundsException e) {
//            	
//            	
//            } finally {
//            	
//            	System.out.println("ECCEZIONE GESTITA");
//            	
//            	
//            }
//               
//               
//               
               
               
//           
//               
//               try {
//            	   
//            	    int [] numbers = {1,2,3,4,5,6};
//      		      
//      		      
//        		  	System.out.println(numbers[8]);
//            	   
//            	   
//               }
//               
//               
//               catch(Exception e) {
//            	  e.getMessage();
//            
//            	   
//               }
//               
//               finally {
//            	   
//            		System.out.println("ECCEZIONE GESTITA");
//            	   
//               }
//               
               
		   
		   
		   
		   try {
			   
			   int [] numbers = {1,2};
				System.out.println(numbers [5]);
			   
			 
			   
			   
		   }
		   
		    
		   catch (Exception e)  {
			   
			   e.getMessage();
			   
			   
		   }
		   
		   
		   finally {
				System.out.println("ECCEZIONE GESTITA");
			   
			   
			   
			   
		   }
		   
		   
		   String names = null;
			System.out.println(names.length());
		   
               
               
                   

}

}
